#!/bin/sh

#compare the external IP against our store IP addresses until we find a match else remove any settings and exit
case $(/usr/bin/curl http://icanhazip.com/) in
$(/usr/bin/dig +short 001.machq.com) ) SWUpdateServer="mhq-swupdate.local:8088";;
$(/usr/bin/dig +short 002.machq.com) ) SWUpdateServer="xserve.local:8088";;
$(/usr/bin/dig +short 003.machq.com) ) SWUpdateServer="servercdr.local:8088";;
* ) /usr/bin/syslog -s -l 3 "Unrecognized external IP"; /usr/bin/defaults delete /Library/Preferences/com.apple.SoftwareUpdate CatalogURL; exit 1;;
esac	

#we've matched the external IP
case $(/usr/bin/sw_vers -productVersion | /usr/bin/awk -F . '{print $2}') in
4) URL="http://${SWUpdateServer}/index.sucatalog" ;;   
5) URL="http://${SWUpdateServer}/index-leopard.merged-1.sucatalog" ;;      
6) URL="http://${SWUpdateServer}/index-leopard-snowleopard.merged-1.sucatalog" ;;    
7) URL="http://${SWUpdateServer}/index-lion-snowleopard-leopard.merged-1.sucatalog" ;;
8) URL="http://${SWUpdateServer}/index-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" ;;
9) URL="http://${SWUpdateServer}/index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" ;;
10) URL="http://${SWUpdateServer}/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog" ;;
*) /usr/bin/syslog -s -l 3 "Unrecognized client OS"; exit 1 ;;
esac

/usr/bin/defaults write /Library/Preferences/com.apple.SoftwareUpdate CatalogURL "${URL}"

/usr/bin/syslog -s -l 5 "Set Software Update Server to ${URL}"
